package com.bookstore.jpa.repositories;

import com.bookstore.jpa.entities.Book;
import jakarta.transaction.Transactional;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.UUID;

public interface BookRepository extends JpaRepository<Book, UUID> {

    /**
     * Derived Query: Automatically generated by Spring Data JPA based on method name.
     */
    List<Book> findBooksByPublisher_Id(UUID id);

    /**
     * Native Query: Uses raw SQL. Useful for database-specific features or performance tuning.
     * Note: This is commented out as an alternative example.
     */
    // @Query(value = "SELECT * FROM book WHERE publisher_id = :id", nativeQuery = true)
    // List<Book> findBooksByPublisherId(@Param("id") UUID id);

    /**
     * JPQL Projection: Returns only specific fields (Title) instead of the whole entity.
     */
    @Query("SELECT b.title FROM Book b WHERE b.publisher.id = :id")
    List<String> findTitlesByPublisherId(@Param("id") UUID id);

    /**
     * Standard JPQL: Retrieves entities based on an association ID.
     */
    @Query("SELECT b FROM Book b WHERE b.publisher.id = :id")
    List<Book> findBooksByPublisherId(@Param("id") UUID id);

    /**
     * JPQL with JOIN FETCH: Optimized query that eagerly loads the 'publisher' association
     * in a single SELECT to avoid the N+1 select problem.
     */
    @Query("SELECT b FROM Book b JOIN FETCH b.publisher WHERE b.publisher.id = :id")
    List<Book> findBooksAndFetchPublisher(@Param("id") UUID id);

    /**
     * DML Operation: Updates a specific field.
     * Requires @Modifying for non-SELECT queries and @Transactional to manage the unit of work.
     */
    @Modifying
    @Transactional
    @Query("UPDATE Book b SET b.title = :newTitle WHERE b.id = :id")
    int updateTitle(@Param("id") UUID id, @Param("newTitle") String newTitle);

}
